// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8mIzSzOAbnzGUcklIfhTCsmMkbJJFC5U',
    appId: '1:558589878953:web:ae9712ddb87e86c15e3fb8',
    messagingSenderId: '558589878953',
    projectId: 'study-app-80065',
    authDomain: 'study-app-80065.firebaseapp.com',
    storageBucket: 'study-app-80065.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx4wsFUoRB3AvggqrujRFuWpOKG_I-IFs',
    appId: '1:558589878953:android:d0fff60facab449e5e3fb8',
    messagingSenderId: '558589878953',
    projectId: 'study-app-80065',
    storageBucket: 'study-app-80065.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyqIefU8TYt-HesCubf05gi9g6YXdXJAs',
    appId: '1:558589878953:ios:db63f1f43e04390b5e3fb8',
    messagingSenderId: '558589878953',
    projectId: 'study-app-80065',
    storageBucket: 'study-app-80065.appspot.com',
    iosClientId: '558589878953-d388k94htnoe4m5e3r4mqf9n3u9g2bdt.apps.googleusercontent.com',
    iosBundleId: 'com.example.eLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyqIefU8TYt-HesCubf05gi9g6YXdXJAs',
    appId: '1:558589878953:ios:a8a4042129a4cbf15e3fb8',
    messagingSenderId: '558589878953',
    projectId: 'study-app-80065',
    storageBucket: 'study-app-80065.appspot.com',
    iosClientId: '558589878953-i6lg2074if94bpbsc6pcf10hhu9b63v5.apps.googleusercontent.com',
    iosBundleId: 'com.example.eLearning.RunnerTests',
  );
}
